In [33]:
import sklearn
import numpy as np

In [34]:
from sklearn.datasets import load_iris
datasets = load_iris()

In [35]:
datasets

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [36]:
x_data = datasets['data']
x_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [37]:
y_data = datasets['target']
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
y_data.shape

(150,)

In [39]:
y_data = y_data.reshape([-1, 1])
y_data[:3]

array([[0],
       [0],
       [0]])

In [40]:
y_data.shape

(150, 1)

In [41]:
# One hot encoding
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(y_data)
y_data = enc.transform(y_data).toarray()
y_data

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [42]:
y_data.shape

(150, 3)

In [44]:
# Min Max Scaling

from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
x_data_minmax = min_max_scaler.fit_transform(x_data)
x_data_minmax[:3]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667]])

In [48]:
# sklearn을 사용하지 않는 경우에는 상수항을 따로 넣어줘야 함
x_0 = np.ones(x_data_minmax.shape[0])
x_data_minmax = np.column_stack((x_0, x_data_minmax))

x_data_minmax[:3]

array([[1.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [1.        , 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [1.        , 0.11111111, 0.5       , 0.05084746, 0.04166667]])

In [50]:
# weight matrix 생성
weights = np.random.uniform(size=(3, 5))
weights

array([[0.62499483, 0.53538091, 0.64729592, 0.10800148, 0.69535364],
       [0.35656169, 0.66357964, 0.7353655 , 0.83634461, 0.30425367],
       [0.32252844, 0.26357368, 0.49549324, 0.54259619, 0.17019918]])

In [51]:
def softmax(z):
    e = np.exp(z)
    p = e / np.sum(np.exp(z), axis=1).reshape([-1, 1])
    return p 

In [53]:
# z = x와 theta_j의 linear combination임
z = x_data_minmax.dot(weights.T)
z[:3]

array([[1.18482352, 1.03300583, 0.73466146],
       [1.02022682, 0.84293915, 0.61679072],
       [1.04259422, 0.85317874, 0.6342423 ]])

In [54]:
z.shape

(150, 3)

In [56]:
# 각각의 class가 나올 확률을 instance별로 찍어줌
softmax(z[:5])

array([[0.40053355, 0.34411636, 0.25535009],
       [0.39911245, 0.33427217, 0.26661538],
       [0.40125391, 0.3320146 , 0.26673149],
       [0.39587469, 0.33333273, 0.27079258],
       [0.40039327, 0.34403316, 0.25557356]])

In [59]:
softmax(z[:5]).sum(axis=1)

array([1., 1., 1., 1., 1.])

In [82]:
def cross_entropy_function(y, x, weights):
    z = x_data_minmax.dot(weights.T)
    result = np.sum(
        np.sum(
        (y * np.log(softmax(z))), axis=1). reshape(([-1, 1]))
    )
    return result

In [83]:
# [1, 0, 0] 같은 값들에 확률값들을 곱해줌
y_data * np.log(softmax(z))

array([[-0.91495774, -0.        , -0.        ],
       [-0.91851208, -0.        , -0.        ],
       [-0.91316086, -0.        , -0.        ],
       [-0.92665756, -0.        , -0.        ],
       [-0.91530803, -0.        , -0.        ],
       [-0.90817349, -0.        , -0.        ],
       [-0.90790858, -0.        , -0.        ],
       [-0.92217797, -0.        , -0.        ],
       [-0.9234123 , -0.        , -0.        ],
       [-0.93552533, -0.        , -0.        ],
       [-0.91852703, -0.        , -0.        ],
       [-0.92983037, -0.        , -0.        ],
       [-0.93068532, -0.        , -0.        ],
       [-0.91702395, -0.        , -0.        ],
       [-0.89713844, -0.        , -0.        ],
       [-0.8936312 , -0.        , -0.        ],
       [-0.88371713, -0.        , -0.        ],
       [-0.90380684, -0.        , -0.        ],
       [-0.91788007, -0.        , -0.        ],
       [-0.90896683, -0.        , -0.        ],
       [-0.93179001, -0.        , -0.   

In [84]:
# 이 값을 최소화 시켜야함
-np.sum(np.sum(y_data * np.log(softmax(z)), axis=1).reshape((-1 ,1)))

172.74975921093034

In [85]:
np.sum(y_data * np.log(softmax(z)), axis=1).shape

(150,)

In [86]:
def minimize_gradient(y, x, initial_weights, iterations = 500000, alpha=0.001):
    cost_history= []
    theta_history = []
    m = y.shape[0]
    theta = np.copy(initial_weights)
    
    number_of_classes = theta.shape[0]
    number_of_weights = theta.shape[1]
    
    for _ in range(iterations):
        original_theta = np.copy(theta)
        for k in range(number_of_classes):        
            for j in range(number_of_weights):
                partial_x = x[:, j]
                partial_entropy = y - softmax(x.dot(original_theta.T))
                theta[k][j]  = original_theta[k][j] + (
                    alpha* partial_entropy[:,k].dot(partial_x.T) ) /150
        if (_ % 10000) == 0:
            print(cross_entropy_function(y,x,theta)/150)
            cost_history.append(cross_entropy_function(y,x,theta))
    return theta, cost_history

In [90]:
theta, cost_history = minimize_gradient(y = y_data, x = x_data_minmax, initial_weights = weights)

-1.1515194415967933
-0.7467079220794834
-0.6122432817217849
-0.5385470182850347
-0.4903520770729072
-0.4553477252611984
-0.4281929138432567
-0.40617569920236457
-0.3877545533048087
-0.3719775495409088
-0.3582190009206593
-0.3460473381710294
-0.33515330140936767
-0.3253083156481435
-0.31633906205234535
-0.3081112555346818
-0.30051891436978656
-0.29347704227820004
-0.2869165056926319
-0.28078036585544436
-0.27502120030395444
-0.26959911256194574
-0.2644802301516894
-0.2596355552701685
-0.2550400742167935
-0.25067205939275916
-0.24651251648334313
-0.24254474239486332
-0.23875396860162038
-0.23512707101838293
-0.2316523321703205
-0.2283192448298457
-0.22511834879721382
-0.22204109437160233
-0.21907972746762772
-0.2162271924023831
-0.21347704919834457
-0.21082340288120174
-0.20826084274500622
-0.205784389943737
-0.20338945207365366
-0.20107178365322245
-0.19882745160111945
-0.1966528049685095
-0.1945444483075841
-0.19249921816051332
-0.19051416223636986
-0.18858652091198536
-0.1867137107490

In [89]:
rand_index = np.random.randint(0, 150, 30)
rand_index

array([ 56, 119,  17,  39,  42, 137, 129,  51,  40,  16, 108,  57, 126,
        37,  79, 147, 102,  17,  80,  26,   9, 141,  32,  40, 133,  20,
        18,  25,  85, 140])

In [93]:
# 3개의 class가 있고, 5개의 변수가 있었기 때문에 3X5의 matrix
theta

array([[ 3.92092254, -1.82443427,  5.01439312, -5.25111263, -4.66639586],
       [ 2.85897192,  1.46567666, -1.35681656,  1.33987544, -1.4500308 ],
       [-5.4758095 ,  1.82129184, -1.7794219 ,  5.39817948,  7.28623316]])

In [95]:
# x와 theta_T_j의 linear combination임. 각각의 label별로 z값을 구해줌
x_data_minmax[rand_index].dot(theta.T)

array([[-0.5860905 ,  2.87228605,  2.51136049],
       [-2.80489039,  3.50056779,  3.14604519],
       [ 5.90461444,  2.30667061, -5.2100523 ],
       [ 5.80111264,  2.44633234, -5.34800821],
       [ 5.91600148,  2.2289882 , -5.73685226],
       [-2.15551692,  3.08690946,  4.04937972],
       [-2.64801921,  3.65811457,  4.19555143],
       [-0.4732653 ,  2.98453176,  2.14951232],
       [ 6.04429508,  2.24324762, -5.35213831],
       [ 6.48287918,  2.11954654, -5.14274982],
       [-3.82815711,  3.61638258,  4.92049322],
       [ 0.65563999,  2.85567805, -0.63211869],
       [-2.05794523,  3.01611678,  3.53016261],
       [ 6.60377127,  2.28954601, -5.99256386],
       [ 0.49007243,  3.11373543, -0.1926832 ],
       [-2.53698929,  2.99519157,  4.50681613],
       [-3.65850819,  3.33802133,  5.75441979],
       [ 5.90461444,  2.30667061, -5.2100523 ],
       [-0.2878751 ,  3.15308831,  0.43249583],
       [ 5.37392314,  2.30749295, -4.69991898],
       [ 5.47010413,  2.59492588, -5.530

In [98]:
# softmax 함수에 넣어서 확률값을 뱉어내도록 함. 이때 가장 큰 확률값이 우리가 찾고자 하는 label임
softmax(x_data_minmax[rand_index].dot(theta.T))

array([[1.82126785e-02, 5.78532384e-01, 4.03254937e-01],
       [1.07219640e-03, 5.87083722e-01, 4.11844082e-01],
       [9.73335612e-01, 2.66498926e-02, 1.44951989e-05],
       [9.66247591e-01, 3.37385062e-02, 1.39023034e-05],
       [9.75557036e-01, 2.44344823e-02, 8.48169376e-06],
       [1.45922300e-03, 2.75980575e-01, 7.22560202e-01],
       [6.72606103e-04, 3.68535990e-01, 6.30791404e-01],
       [2.14957186e-02, 6.82423775e-01, 2.96080507e-01],
       [9.78130387e-01, 2.18586237e-02, 1.09897703e-05],
       [9.87415579e-01, 1.25755991e-02, 8.82172366e-06],
       [1.24786704e-04, 2.13447378e-01, 7.86427835e-01],
       [9.70756407e-02, 8.76142312e-01, 2.67820475e-02],
       [2.33616634e-03, 3.73371269e-01, 6.24292565e-01],
       [9.86796375e-01, 1.32002854e-02, 3.33970962e-06],
       [6.53964378e-02, 9.01563786e-01, 3.30397759e-02],
       [7.14574737e-04, 1.80569035e-01, 8.18716390e-01],
       [7.49652857e-05, 8.19246069e-02, 9.18000428e-01],
       [9.73335612e-01, 2.66498

In [102]:
# 확률값이 가장 큰 것의 index를 뽑아서 y_pred에 저장
y_pred = np.argmax(softmax(x_data_minmax[rand_index].dot(theta.T)), axis=1)
y_pred

array([1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 2, 1, 2, 0, 1, 2, 2, 0, 1, 0, 0, 2,
       0, 0, 1, 0, 0, 0, 1, 2])

In [103]:
y_true = np.argmax(y_data[rand_index], axis=1)
y_true

array([1, 2, 0, 0, 0, 2, 2, 1, 0, 0, 2, 1, 2, 0, 1, 2, 2, 0, 1, 0, 0, 2,
       0, 0, 2, 0, 0, 0, 1, 2])

In [105]:
# 93% 정도 맞는 분류기이다
sum(y_pred == y_true) / len(rand_index)

0.9333333333333333