In [1]:
import numpy as np

In [ ]:
77	79.775152
1	21	23.177279
2	22	25.609262
3	20	17.857388
4	36	41.849864

In [14]:
X = np.array([[1, 1, 1, 1, 1], [77, 21, 22, 20 ,36]]).T
X

array([[ 1, 77],
       [ 1, 21],
       [ 1, 22],
       [ 1, 20],
       [ 1, 36]])

In [21]:
y = np.array([[79.775152, 23.177279, 25.609262, 17.857388, 41.849864]]).T
y

array([[79.775152],
       [23.177279],
       [25.609262],
       [17.857388],
       [41.849864]])

In [38]:
XXT = X.T.dot(X)
XXT

array([[   5,  176],
       [ 176, 8550]])

In [39]:
XXT_inversed = np.linalg.inv(XXT)
XXT_inversed

array([[ 7.26176321e-01, -1.49481909e-02],
       [-1.49481909e-02,  4.24664515e-04]])

In [44]:
XT_dot_y = X.T.dot(y)
XT_dot_y

array([[ 188.268945],
       [9056.556191]])

In [45]:
XXT_inversed.dot(XT_dot_y)

array([[1.33731868],
       [1.03171791]])

In [46]:
class LinearRegression(object):
    def __init__(self, fit_intercept=True, copy_X=True):
        self.fit_intercept = fit_intercept
        self.copy_X = copy_X

        self._coef = None
        self._intercept = None
        self._new_X = None

    def fit(self, X, y):
        XXT = X.T.dot(X)
        XXT_inversed = np.linalg.inv(XXT)
        XT_dot_y = X.T.dot(y)
        return XXT_inversed.dot(XT_dot_y)

    def predict(self, X):
        pass

    @property
    def coef(self):
        return self._coef

    @property
    def intercept(self):
        return self._intercept