## Nympy

- Numerical Python
- 파이썬 고성능 과학 계산용 기초 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준
- 한글로 넘파이로 주로 통칭
- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원함
- 선형대수와 관련된 다양한 기능을 제공함

In [2]:
import numpy as np

In [4]:
weight_vector = np.array([[1], [1], [1]]) # weight Vector
x_vector = np.array([[3], [4], [5]])

## 행렬의 연산

In [5]:
weight_vector

array([[1],
       [1],
       [1]])

In [6]:
x_vector

array([[3],
       [4],
       [5]])

In [7]:
weight_vector.T

array([[1, 1, 1]])

In [8]:
weight_vector.T.dot(x_vector)

array([[12]])

In [9]:
weight_vector.dot(x_vector)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [10]:
import pandas as pd

In [19]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', "AGE", 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

In [20]:
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [21]:
df_data['weight_0'] = 1
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  weight_0  
0     15.3  396.90   4.98  24.0         1  
1     17.8  396.90   9.14  21.6         1  
2     17.8  392.83   4.03  34.7         1  
3     18.7  394.63   2.94  33.4         1  
4     18.7  396.90   5.33  36.2         1

In [23]:
df_data.to_numpy()

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 4.9800e+00, 2.4000e+01,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 9.1400e+00, 2.1600e+01,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 4.0300e+00, 3.4700e+01,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 5.6400e+00, 2.3900e+01,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 6.4800e+00, 2.2000e+01,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 7.8800e+00, 1.1900e+01,
        1.0000e+00]])

In [24]:
df_data.shape

(506, 15)