## Operations b/t arrays

- Numpy는 array 간의 기본적인 사칙 연산을 지원함

### Element-wise operations

- Array 간 shape이 같을 때 일어나는 연산

In [1]:
import numpy as np

In [2]:
test_a = np.array([[1,2,3],[1,2,3]], float)

In [3]:
test_a + test_a

array([[2., 4., 6.],
       [2., 4., 6.]])

In [4]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
test_a * test_a

array([[1., 4., 9.],
       [1., 4., 9.]])

In [13]:
test_b = np.array([[1,2,3]])
test_b

array([[1, 2, 3]])

In [15]:
test_a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [16]:
test_a - test_b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
test_c = np.array([[1,2]])
test_c

array([[1, 2]])

In [20]:
test_a * test_c

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [14]:
test_a + test_b

array([[2., 4., 6.],
       [2., 4., 6.]])

In [8]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

## Dot product

- Matrix의 기본 연산
- dot 함수 사용

In [21]:
test_a = np.arange(1, 7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
test_b = np.arange(7, 13).reshape(3,2)
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

## Transpose

- transpose 또는 T attribute 사용

In [24]:
test_a = np.arange(1, 7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## broadcasting

- Shape이 다른 배열 간 연산을 지원하는 기능

In [32]:
test_matrix = np.arange(1,7).reshape(2,3)
test_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
scalar = 3

In [34]:
test_matrix + scalar

array([[4, 5, 6],
       [7, 8, 9]])

In [35]:
test_matrix - scalar

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [36]:
test_matrix * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [37]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [38]:
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [39]:
test_matrix ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [41]:
test_matrix = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
test_matrix

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [42]:
test_scalar = np.array([[0,1,2]])
test_scalar

array([[0, 1, 2]])

In [43]:
test_matrix + test_scalar

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [45]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iteration_max = 100000000

vector = list(range(iteration_max))
scalar = 2

### for loop, list comprehension, numpy 의 성능 비교

In [46]:
%timeit scalar_vector_product(scalar, vector) # for loop 을 이용한 성능
%timeit [scalar * value for value in range(iteration_max)] # list comprehension을 이용한 성능
%timeit np.arange(iteration_max) * scalar # numpy를 이용한 성능

10.9 s ± 417 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
8.71 s ± 649 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
456 ms ± 5.72 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
