## boolean index

- numpy 배열은 특정 조건에 따른 값을 배열 형태로 추출할 수 있음
- Comparision operation 함수들도 모두 사용가능

In [1]:
import numpy as np

In [2]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [3]:
test_array

array([1., 4., 0., 2., 3., 8., 9., 7.])

In [4]:
# 조건이 True인 index의 element만 추출
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [6]:
condition = test_array < 3
condition

array([ True, False,  True,  True, False, False, False, False])

In [7]:
test_array[condition]

array([1., 0., 2.])

In [8]:
A = np.array([[13,17,14,10,15],[1,1,1,1,1], [16,16,16,16,16],[16,16,16,16,16],[1,1,1,1,1]])
A

array([[13, 17, 14, 10, 15],
       [ 1,  1,  1,  1,  1],
       [16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16],
       [ 1,  1,  1,  1,  1]])

In [9]:
B = A < 15
B

array([[ True, False,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [10]:
B.astype(np.int)

/var/folders/w3/8l1p0j1d51s69f3vlw1939ym0000gn/T/ipykernel_1332/839819474.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B.astype(np.int)


array([[1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

## fancy index

- numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [14]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # 반드시 int로 선언
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [26]:
a.take(b)  #take 함수 : bracket index와 같은 효과, take가 더 명확한 표현

array([1, 1, 4, 4, 1])

- matrix 형태에도 적용 가능

In [23]:
a = np.array([[1,4], [9, 16]], int)
a

array([[ 1,  4],
       [ 9, 16]])

In [25]:
a = np.array([[1,4], [9, 16]], int)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1 ,1, 1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1,  4, 16, 16,  4])