### All & Any

- Array의 데이터 전부 (and) 또는 일부 (or)가 조건에 만족 여부 반환

In [2]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# any는 하나라도 조건에 만족하면 True
np.any(a>5), np.any(a<0)

(True, False)

In [6]:
# and는 모두가 조건에 만족해야 True
np.all(a>5), np.all(a<10)

(False, True)

In [7]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [8]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

### comparision operation #1

- Numpy는 배열의 크기가 동일할 때 element간 비교의 결과를 Boolean Type으로 반환하여 돌려줌\

In [10]:
test_a = np.array([1,2,3], float)
test_b = np.array([5,1,2], float)
test_a, test_b

(array([1., 2., 3.]), array([5., 1., 2.]))

In [11]:
test_a > test_b

array([False,  True,  True])

In [13]:
# any는 하나라도 true면 true
(test_a > test_b).any()

True

### comparision operation #1

In [38]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a< 3)

array([ True, False, False])

In [17]:
b = np.array([False, False, True], bool)
np.logical_not(b)

array([ True,  True, False])

In [18]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([False,  True,  True])

## np.where

In [20]:
a

array([1., 3., 0.])

In [39]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a< 3)

array([ True, False, False])

In [26]:
a > 0

array([ True,  True, False])

In [35]:
# where(condition, True, False)
np.where(a > 0, 3, 2)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [37]:
# True인 값의 index 출력
np.where(a>10)

(array([6, 7, 8, 9]),)

In [34]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

(array([6, 7, 8, 9]),)

In [30]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [32]:
np.isfinite(a)

array([ True, False, False])

## argmax & argmin

- array 내 최대값 또는 최소값의 index를 반환함

In [3]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

- axis 기반의 반환

In [5]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [6]:
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))