### arange

- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [1]:
import numpy as np

In [2]:
np.arange(30) # arange: list의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
np.arange(0, 5, 0.5) # floating point도 표시가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [4]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
np.arange(0, 5, 0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [8]:
np.arange(30).reshape(5, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

## ones, zeros, and empty

#### zeros : 0으로 가득찬 ndarray 생성

In [14]:
# 10 - zero vector 생성
np.zeros(shape=(10, ), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [15]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### ones : 1로 가득찬 ndarray 생성

- np.ones(shape, dtype, order)

In [16]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### empty

- shape만 주어지고 비어있는 ndarray 생성 (memory initialization 이 되지 않음)

In [18]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [19]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

#### something_like

- ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환

In [21]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [22]:
test_matrix = np.arange(30).reshape(5, 6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### identity

- 단위 행렬을 생성함
- n -> number of rows

In [23]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [24]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### eye

- 대각선이 1인 행렬, k값의 시작 index의 변경이 가능

In [25]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(3,5,k=2)  # k -> start index 

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### diag

- 대각 행렬의 값을 추출함

In [28]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [29]:
np.diag(matrix, k=1)

array([1, 5])

### random sampling

- 데이터 분포에 따른 sampling으로 array를 생성

In [34]:
# 균등분포에서 임의의 난수 생성
# 0과 1사이에서 10개의 난수 생성
np.random.uniform(low=0.0, high=1.0, size=10).reshape(2,5) 

array([[0.15078853, 0.6070397 , 0.52597249, 0.00353477, 0.15520173],
       [0.40010579, 0.18396509, 0.03688709, 0.9229148 , 0.83626107]])

In [38]:
# 정규분포에서 임의의 난수 생성
# 평균이 0, 표준편차가 1인 난수 10개 생성
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-0.5348125 , -0.30614422,  0.06214426, -0.85929229, -0.07720322],
       [-0.58490976,  0.83287612, -1.26460861,  0.23319751, -0.40359761]])