### reshape

- Array의 Shape의 크기를 변경함 (element의 개수는 동일함)

In [1]:
import numpy as np

In [2]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [4]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [6]:
# -1: size를 기반으로 row 개수 변경
np.array(test_matrix).reshape(-1, 2).shape

(4, 2)

In [7]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [8]:
np.array(test_matrix).reshape(2, 2, 2).shape

(2, 2, 2)

### flatten

- 다차원 array를 1차원 array로 변환해줌

In [10]:
test_matrix = test_matrix = [[1,2,3,4], [1,2,5,8], [1,2,3,4], [1,2,5,8]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [11]:
np.array(test_matrix).flatten().shape

(16,)