### indexing

In [1]:
import numpy as np
a = np.array([[1,2,3], [4.5, 5, 6]], int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
print(a[0,0]) # Two dimensional array representation #1
print(a[0][0]) # Two dimensional array representation #2

1
1


In [6]:
# Matrix 0,0에 12 할당
a[0,0] = 12

In [7]:
a[0][1] = 5
a

array([[12,  5,  3],
       [ 4,  5,  6]])

### slicing

- List와 달리 행과 열 부분을 나눠서 slicing 가능
- Matrix의 부분 집합을 추출할 때 유용함

In [8]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# 전체 row 의 2열 이상
a[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [11]:
# 1 Row의 1열 ~ 2열
a[1, 1:3]

array([7, 8])

In [17]:
# 1 Row ~ 2 Row의 전체인데, 범위가 넘어가서 1만 출력
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [18]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
test_array_a = np.array([[0,1,2,3,4], [5,6,7,8,9], [10, 11, 12, 13, 14]])
test_array_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
test_array_a[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [23]:
test_array_a[::2, ::3]

array([[ 0,  3],
       [10, 13]])