In [1]:
import numpy as np

In [6]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.array([1,2], [1,2], dtype=np.int)

/var/folders/w3/8l1p0j1d51s69f3vlw1939ym0000gn/T/ipykernel_25849/3643746761.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def n_size_ndarray_creation(n, dtype=np.int):


In [14]:
np.array([[1,2], [1,2]], np.int).shape

/var/folders/w3/8l1p0j1d51s69f3vlw1939ym0000gn/T/ipykernel_25849/3241342968.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([[1,2], [1,2]], np.int).shape


(2, 2)

In [24]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=np.int)
    elif type == 1:
        return np.ones(shape=shape, dtype=np.int)
    elif type == 99:
        return np.empty(shape=shape, dtype=np.int)

/var/folders/w3/8l1p0j1d51s69f3vlw1939ym0000gn/T/ipykernel_25849/3390424962.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):


In [22]:
import random

In [23]:
np.random.rand(5)

array([0.21114411, 0.78067346, 0.35328993, 0.67597543, 0.81608773])

In [35]:
def change_shape_of_ndarray(X, n_row):
    return X.reshape(n_row, -1)

In [27]:
test_matrix = [[1,2,3,4], [1,2,3,4]]

In [34]:
np.array(test_matrix).reshape(2, -1)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [131]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if axis == 0:
            if X_1.shape[1:] == X_2.shape[1:]:
                return np.concatenate((X_1, X_2), axis=0)
            else:
                return False
        elif axis == 1:
            if X_1.shape[1:] == X_2.shape[1:]:
                return np.concatenate((X_1, X_2), axis=1)
            else:
                return False
    except:
        pass


In [45]:
X_1 = np.array([1,2,3])
X_2 = np.array([2,3,4])
X_1.shape[0]

3

In [128]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [122]:
a.shape[1:]

()

In [133]:
np.concatenate((a, b), axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [134]:
concat_ndarray(a,b, 1)

In [90]:
a = np.array([1,2])
b = np.array([2,3,4])
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [135]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis == 0:
        pass
    elif axis == 1:
        pass
    else:
        


In [137]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [144]:
X.mean(axis=1) / X.std(axis=1)

array([ 1.,  5.,  9., 13., 17., 21.], dtype=float32)

In [147]:
X.mean(axis=0) / X.std(axis=0)

array([1.46385, 1.75662], dtype=float32)

In [152]:
def save_ndarray(X, filename="test.npy"):
    return np.save(filename, X)

In [150]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
X

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.]], dtype=float32)

In [151]:
filename = "test.npy"

In [153]:
save_ndarray(X, filename)

In [167]:
def boolean_index(X, condition):
    return X[eval(str("X") + condition)]

In [168]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)

In [170]:
boolean_index(X, ">= 6")

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31.],
      dtype=float32)

In [206]:
def find_nearest_value(X, target_value):
    gap = []
    for i in X:
        gap.append(abs(i - target_value))
    return min(gap)

In [212]:
X = np.random.uniform(0, 1, 100)
target_value = 0.3

In [213]:
find_nearest_value(X, target_value)

0.0069872264081586866

In [222]:
def get_n_largest_values(X, n):
    return sorted(X)[:n]

In [223]:
X = np.random.uniform(0, 1, 100)
n = 3

In [224]:
get_n_largest_values(X, 3)

[0.004934568457367172, 0.01069165189607757, 0.025360890325371033]

In [225]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    return None

In [226]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [227]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.arange(n**2).reshape(n,n)

/var/folders/w3/8l1p0j1d51s69f3vlw1939ym0000gn/T/ipykernel_25849/4083491500.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def n_size_ndarray_creation(n, dtype=np.int):


In [229]:
n = 4

In [228]:
n_size_ndarray_creation(n, dtype=np.int)

/var/folders/w3/8l1p0j1d51s69f3vlw1939ym0000gn/T/ipykernel_25849/3628035126.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  n_size_ndarray_creation(n, dtype=np.int)


In [232]:
np.arange(n**2).reshape(n,n)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [233]:
X = np.arange(12, dtype=np.float32).reshape(6,2)

In [234]:
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [238]:
X.mean(axis=0)

array([5., 6.], dtype=float32)

In [243]:
(X - X.mean(axis=1)) / X.std(axis=1)

ValueError: operands could not be broadcast together with shapes (6,2) (6,) 

In [255]:
X.shape

(6, 2)

In [256]:
X - X.mean(axis=1).reshape(1, -1)

ValueError: operands could not be broadcast together with shapes (6,2) (1,6) 

In [257]:
n_row, n_column = X.shape

In [259]:
X - X.std(axis=1).reshape(n_row, -1)

array([[-0.5,  0.5],
       [ 1.5,  2.5],
       [ 3.5,  4.5],
       [ 5.5,  6.5],
       [ 7.5,  8.5],
       [ 9.5, 10.5]], dtype=float32)

In [261]:
X.std(axis=1).reshape(n_row, -1).shape

(6, 1)

In [265]:
def normalize_ndarray(X, axis, dtype=np.float32):
    n_row, n_column = X.shape
    if axis == 0:
        return (X - X.mean(axis=0).reshape(n_column, -1)) / X.std(axis=0).reshape(n_column, -1)
    elif axis == 1:
        return (X - X.mean(axis=1).reshape(n_row, -1)) / X.std(axis=1).reshape(n_row, -1)
    elif axis == 99:
        return (X - X.mean()) / X.std()

In [267]:
normalize_ndarray(X, axis=99)

array([[-1.593255  , -1.3035723 ],
       [-1.0138896 , -0.7242068 ],
       [-0.4345241 , -0.14484136],
       [ 0.14484136,  0.4345241 ],
       [ 0.7242068 ,  1.0138896 ],
       [ 1.3035723 ,  1.593255  ]], dtype=float32)

In [268]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)

In [269]:
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return np.where(condition)

In [271]:
X

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.]], dtype=float32)

In [270]:
boolean_index(X, "==3")

(array([0]), array([3]))

In [283]:
X = np.random.uniform(0, 1, 100)

In [286]:
X

array([0.79089266, 0.45170307, 0.46405514, 0.82787288, 0.09001375,
       0.57888602, 0.71189241, 0.59262053, 0.03841105, 0.19973792,
       0.44651658, 0.7539698 , 0.10661048, 0.58462877, 0.95217746,
       0.83475429, 0.22599355, 0.25584765, 0.01081854, 0.78144058,
       0.18364924, 0.98641255, 0.5607961 , 0.85233202, 0.12811111,
       0.36617879, 0.80659806, 0.10915352, 0.03430975, 0.20210276,
       0.18715847, 0.13802659, 0.45906353, 0.63233726, 0.41697747,
       0.56528053, 0.45675689, 0.37646985, 0.44747874, 0.88873208,
       0.75387413, 0.55761789, 0.73876627, 0.71180985, 0.96159602,
       0.62302249, 0.39153983, 0.62083639, 0.46614129, 0.23138557,
       0.27791244, 0.48496622, 0.68210017, 0.52143512, 0.55861616,
       0.00716162, 0.31397555, 0.31858914, 0.24460561, 0.22163186,
       0.94947447, 0.15632064, 0.26594721, 0.87860908, 0.37429183,
       0.10862288, 0.09411945, 0.82276098, 0.52341625, 0.77342908,
       0.29890182, 0.54495091, 0.70145093, 0.87461069, 0.79773

In [291]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X - target_value))]

In [292]:
find_nearest_value(X, 0.3)

0.29890182321546355

In [293]:
import numpy as np

In [294]:
np.arange(32).reshape(4, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])