In [14]:
import pandas as pd
import numpy as np
import linear_model
import imp
imp.reload(linear_model)

<module 'linear_model' from '/Users/kwon-yong-geun/workspace/TIL/TIL/machine_learning/chapter6_linear_regression/lab_normal_equation/linux_mac/linear_model.py'>

In [15]:
df = pd.read_csv("./test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [16]:
X = df["x"].values.reshape(-1,1)
y = df["y"].values

In [17]:
lr = linear_model.LinearRegression(fit_intercept=True)
lr.fit(X, y)
lr.intercept # -0.46181077366099998
lr.coef # array([ 1.01433536])

array([1.01433536])

In [18]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

In [20]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression()
sk_lr.fit(X, y)
sk_lr.intercept_ # -0.46181077366117762
sk_lr.coef_ # array([ 1.01433536])
np.isclose(lr.coef, sk_lr.coef_) #True

array([ True])

In [21]:
df_test = pd.read_csv("./train.csv")
df_test.head()
X_test = df["x"].values.reshape(-1,1)

In [22]:
lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

## Multiple variable

In [23]:
df = pd.read_csv("./mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [24]:
y = df["average_points_scored"].values
X = df.iloc[:,:-1].values
mu_X = np.mean(X, axis=0)
std_X = np.std(X, axis=0)

In [25]:
rescaled_X = (X - mu_X) / std_X # RESCALED

In [26]:
lr.fit(rescaled_X, y)
lr.coef # array([-1.67779283, 0.28359762, 2.68586629, 1.12816882])
lr.intercept # 11.790740740740738

11.79074074074074

In [27]:
lr.coef, lr.intercept

(array([-1.67779283,  0.28359762,  2.68586629,  1.12816882]),
 11.79074074074074)

In [28]:
sk_lr.fit(rescaled_X, y)
sk_lr.coef_ # array([-1.67779283, 0.28359762, 2.68586629, 1.12816882])
sk_lr.intercept_ # 11.790740740740736

11.790740740740736

In [29]:
sk_lr.coef_, sk_lr.intercept_

(array([-1.67779283,  0.28359762,  2.68586629,  1.12816882]),
 11.790740740740736)